import { 
  FileText, 
  Image as ImageIcon, 
  FileCheck, 
  Sparkles, 
  Video, 
  Mic, 
  QrCode,
  Wand2,
  Shield,
  Palette,
  Database,
  LucideIcon
} from 'lucide-react';

export type ToolCategory = 'All' | 'Image' | 'Video & Audio' | 'Text & Utilities' | 'Developer';

export interface ToolDefinition {
  id: string;
  name: string;
  description: string;
  category: ToolCategory;
  href: string;
  iconName: string;
  badge?: string;
  popular?: boolean;
  accentColor: string;
}

export const TOOLS: ToolDefinition[] = [
  {
    id: 'image-to-pdf',
    name: 'Image to PDF Converter',
    description: 'Merge multiple images (PNG, JPG, WebP) into a single high-quality PDF document with custom order and layout.',
    category: 'Image',
    href: '/tools/image-to-pdf',
    iconName: 'FileText',
    badge: 'Multi-Page',
    popular: true,
    accentColor: 'from-blue-500 to-indigo-600',
  },
  {
    id: 'pdf-compressor',
    name: 'Smart PDF Compressor',
    description: 'Compress PDF documents up to 90% or hit target size limits (100KB, 200KB, 500KB) 100% client-side.',
    category: 'Image',
    href: '/tools/pdf-compressor',
    iconName: 'FileCheck',
    badge: 'Target KB',
    popular: true,
    accentColor: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'image-converter',
    name: 'Universal Image Converter',
    description: 'Convert images instantly between PNG, JPG, and WebP formats using browser-native HTML5 Canvas rendering.',
    category: 'Image',
    href: '/tools/image-converter',
    iconName: 'ImageIcon',
    popular: true,
    accentColor: 'from-indigo-500 to-purple-600',
  },
  {
    id: 'image-compressor',
    name: 'Smart Image Compressor',
    description: 'Reduce image file sizes by up to 90% with custom quality slider and real-time estimated file size preview.',
    category: 'Image',
    href: '/tools/image-compressor',
    iconName: 'FileCheck',
    popular: true,
    accentColor: 'from-purple-500 to-pink-600',
  },
  {
    id: 'image-upscaler',
    name: 'Image to 4K Upscaler',
    description: 'Enhance and upscale image resolutions to 2x, 4x, or 4K with interactive Before/After comparison slider.',
    category: 'Image',
    href: '/tools/image-upscaler',
    iconName: 'Sparkles',
    badge: 'AI Powered',
    popular: true,
    accentColor: 'from-amber-500 to-orange-600',
  },
  {
    id: 'magic-eraser',
    name: 'Magic Eraser & BG Remover',
    description: 'Brush over unwanted objects/people to erase them or remove image backgrounds completely with AI canvas mask.',
    category: 'Image',
    href: '/tools/magic-eraser',
    iconName: 'Wand2',
    badge: 'AI Brush',
    popular: true,
    accentColor: 'from-pink-500 to-rose-600',
  },
  {
    id: 'video-to-audio',
    name: 'Video to Audio Extractor',
    description: 'Extract MP3, WAV, or AAC audio directly from MP4 and WebM videos in your browser using WebAssembly.',
    category: 'Video & Audio',
    href: '/tools/video-to-audio',
    iconName: 'Video',
    badge: 'Browser Wasm',
    popular: true,
    accentColor: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'video-upscaler',
    name: 'Video to 4K Upscaler',
    description: 'Enhance video resolution, clarity, and sharpness up to 4K Ultra HD (3840x2160) with real-time browser super-sampling and audio preservation.',
    category: 'Video & Audio',
    href: '/tools/video-upscaler',
    iconName: 'Film',
    badge: '4K Ultra HD',
    popular: true,
    accentColor: 'from-amber-500 via-orange-500 to-red-600',
  },
  {
    id: 'instagram-downloader',
    name: 'Instagram Reel & Video Downloader',
    description: 'Download Instagram Reels, IGTV videos, and carousel photos in high resolution MP4/JPG with MP3 audio extraction.',
    category: 'Video & Audio',
    href: '/tools/instagram-downloader',
    iconName: 'Instagram',
    badge: 'Reels HD',
    popular: true,
    accentColor: 'from-pink-500 via-rose-500 to-amber-500',
  },
  {
    id: 'youtube-downloader',
    name: 'YouTube Video & Shorts Downloader',
    description: 'Download YouTube videos and Shorts in 1080p, 720p, or 480p MP4 formats or extract high quality MP3 audio.',
    category: 'Video & Audio',
    href: '/tools/youtube-downloader',
    iconName: 'Youtube',
    badge: '1080p & MP3',
    popular: true,
    accentColor: 'from-red-600 to-rose-600',
  },
  {
    id: 'facebook-downloader',
    name: 'Facebook Video & Reels Downloader',
    description: 'Download Facebook watch videos, public reels, and clips in HD & SD MP4 quality with fast stream link parsing.',
    category: 'Video & Audio',
    href: '/tools/facebook-downloader',
    iconName: 'Facebook',
    badge: 'FB HD',
    popular: true,
    accentColor: 'from-blue-600 to-indigo-600',
  },
  {
    id: 'speech-to-text',
    name: 'Speech to Text Dictation',
    description: 'Real-time continuous voice recording and transcription using Web Speech API with copy and text export options.',
    category: 'Text & Utilities',
    href: '/tools/speech-to-text',
    iconName: 'Mic',
    accentColor: 'from-rose-500 to-red-600',
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Create custom, downloadable QR codes for URLs, WiFi passwords, vCards, or text in PNG and SVG formats.',
    category: 'Text & Utilities',
    href: '/tools/qr-generator',
    iconName: 'QrCode',
    accentColor: 'from-cyan-500 to-blue-600',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate ultra-secure random passwords and passphrases with custom length, symbols, and strength score.',
    category: 'Text & Utilities',
    href: '/tools/password-generator',
    iconName: 'Shield',
    accentColor: 'from-violet-500 to-indigo-600',
  },
  {
    id: 'color-palette',
    name: 'Color Palette Extractor',
    description: 'Upload any photo or graphic to automatically extract dominant color palettes with HEX/RGB codes & one-click copy.',
    category: 'Text & Utilities',
    href: '/tools/color-palette',
    iconName: 'Palette',
    accentColor: 'from-fuchsia-500 to-purple-600',
  },
  {
    id: 'dummy-data',
    name: 'Dummy Data Generator',
    description: 'Generate realistic mock datasets (Users, Products, Orders) in JSON or CSV format for developer testing.',
    category: 'Developer',
    href: '/tools/dummy-data',
    iconName: 'Database',
    badge: 'Developer',
    accentColor: 'from-teal-500 to-emerald-600',
  },
  {
    id: 'word-counter',
    name: 'Word & Character Counter',
    description: 'Count words, characters with/without spaces, paragraphs, and reading time in real-time with one-click case converters.',
    category: 'Text & Utilities',
    href: '/tools/word-counter',
    iconName: 'Type',
    badge: 'Live Stats',
    popular: true,
    accentColor: 'from-blue-500 to-cyan-600',
  },
  {
    id: 'exact-resizer',
    name: 'Exact Image Resizer',
    description: 'Resize photos to exact pixel dimensions (e.g., 300x300) or compress to target file size limits (under 50KB) for online form applications.',
    category: 'Image',
    href: '/tools/exact-resizer',
    iconName: 'Crop',
    badge: 'Form Ready',
    popular: true,
    accentColor: 'from-emerald-500 to-green-600',
  },
  {
    id: 'age-calculator',
    name: 'Age & Date Calculator',
    description: 'Calculate exact age in years, months, and days, plus total days lived and a countdown to your next birthday.',
    category: 'Text & Utilities',
    href: '/tools/age-calculator',
    iconName: 'Calendar',
    popular: true,
    accentColor: 'from-indigo-500 to-purple-600',
  },
  {
    id: 'pdf-tools',
    name: 'PDF Splitter & Merger',
    description: 'Merge multiple PDF files into a single document or split and extract specific page ranges with privacy-first client processing.',
    category: 'Text & Utilities',
    href: '/tools/pdf-tools',
    iconName: 'FileStack',
    badge: 'pdf-lib',
    popular: true,
    accentColor: 'from-rose-500 to-orange-600',
  },
];
